application:
  name: KTB_10WEEK
  auth:
    token:
      secretkey: SECRET_KEY
      issuer : KTB_10WEEK
      access-token-ttl-millis: 900000 # 15분
      refresh-token-ttl-millis: 604800000 # 7일
    cookie:
      refresh-token-cookie-name: Refresh-Token
      refresh-token-cookie-path: /auth/access/token/refresh
      refresh-token-cookie-max-age: 604800 # 7일
      refresh-token-cookie-same-site: Lax


springdoc:
  api-docs:
    path: /api-docs # API ?? ?? (???: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui.html # Swagger UI ??
  info:
    title: My API Specification
    version: v1.0.0
    description: This document descript my project how to use

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/KTB_7WEEK?serverTimezone=UTC&useSSL=false
    username: root
    password: Hss@857942
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

file:
  upload-dir:
    profile: uploads/profile
    article: uploads/article
  logo: logo

