server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:bootsecurity.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bootsecurity

spring:
  application:
    name: Today SeaFood
    auth:
      cors:
        allowed-origins: https://localhost:5173
        allowed-methods: GET,POST,PATCH,DELETE,OPTIONS
        allowed-headers: "*"
        exposed-headers: Authorization
        max-age: 3600
        url-source: /**
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            ssl:
              use-insecure-trust-manager: true
          routes:
            - id: api-service
              uri: https://localhost:8444
              predicates:
                - Path=/api/**
